import type { AnswerMap } from "./types";

export type GoldenSeed = {
  id: string;
  targetGameId: string;
  persona: string;
  answers: AnswerMap;
  notes: string[];
};

// Generated by scripts/expand-golden-seeds.ts for Mini v0.1.
// One full-answer core target-player seed per game. Do not edit scoring.ts for seed fixes.
export const goldenSeeds: GoldenSeed[] = [
  {
    "id": "seed-honor-of-kings",
    "targetGameId": "honor-of-kings",
    "persona": "核心目标玩家：想玩《王者荣耀》这类强对抗、MOBA 对抗、团队配合体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=王者荣耀",
      "coreTags=pvp, moba, team, ranked, short_session, reflex, social_pressure, hype",
      "avoidSignals=solo_only, low_pressure, no_pvp, no_team_dependency"
    ]
  },
  {
    "id": "seed-lol-wild-rift",
    "targetGameId": "lol-wild-rift",
    "persona": "核心目标玩家：想玩《英雄联盟手游》这类强对抗、MOBA 对抗、团队配合体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "D",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=英雄联盟手游",
      "coreTags=pvp, moba, team, ranked, lane_phase, macro, reflex, high_pressure",
      "avoidSignals=solo_only, low_pressure, no_pvp, no_team_dependency"
    ]
  },
  {
    "id": "seed-valorant",
    "targetGameId": "valorant",
    "persona": "核心目标玩家：想玩《VALORANT》这类强对抗、tactical shooter、排位成长体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "D",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=VALORANT",
      "coreTags=pvp, tactical_shooter, ranked, team, aim, low_ttk, high_pressure, skill_mastery",
      "avoidSignals=low_pressure, no_pvp, no_aim, solo_only"
    ]
  },
  {
    "id": "seed-apex-legends",
    "targetGameId": "apex-legends",
    "persona": "核心目标玩家：想玩《Apex Legends》这类强对抗、生存淘汰、团队配合体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "B"
    },
    "notes": [
      "target=Apex Legends",
      "coreTags=pvp, battle_royale, team, aim, movement, hero_skill, high_pressure, long_session",
      "avoidSignals=low_pressure, no_pvp, no_aim, solo_only"
    ]
  },
  {
    "id": "seed-peace-elite",
    "targetGameId": "peace-elite",
    "persona": "核心目标玩家：想玩《和平精英》这类强对抗、生存淘汰、团队配合体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=和平精英",
      "coreTags=pvp, battle_royale, team, survival, aim, mobile_shooter, high_pressure, ranked",
      "avoidSignals=low_pressure, no_pvp, no_aim, solo_only"
    ]
  },
  {
    "id": "seed-cs2",
    "targetGameId": "cs2",
    "persona": "核心目标玩家：想玩《CS2》这类强对抗、tactical shooter、aim体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "B",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "D",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=CS2",
      "coreTags=pvp, tactical_shooter, aim, low_ttk, economy_rounds, ranked, high_pressure, reflex",
      "avoidSignals=low_pressure, no_pvp, no_aim, casual_only"
    ]
  },
  {
    "id": "seed-overwatch-2",
    "targetGameId": "overwatch-2",
    "persona": "核心目标玩家：想玩《守望先锋2》这类强对抗、hero shooter、团队配合体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=守望先锋2",
      "coreTags=pvp, hero_shooter, team, objective, hero_skill, fast_feedback, social_pressure",
      "avoidSignals=solo_only, no_team_dependency, no_pvp"
    ]
  },
  {
    "id": "seed-naraka-bladepoint",
    "targetGameId": "naraka-bladepoint",
    "persona": "核心目标玩家：想玩《永劫无间》这类强对抗、melee action、生存淘汰体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "D",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=永劫无间",
      "coreTags=pvp, melee_action, battle_royale, timing, combo, high_pressure, skill_mastery",
      "avoidSignals=low_pressure, no_pvp, no_reflex"
    ]
  },
  {
    "id": "seed-genshin-impact",
    "targetGameId": "genshin-impact",
    "persona": "核心目标玩家：想玩《原神》这类开放世界、探索发现、character collection体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=原神",
      "coreTags=open_world, exploration, character_collection, element_team_building, anime, long_term, story, cozy_adventure",
      "avoidSignals=no_collection, no_long_term, no_gacha_like"
    ]
  },
  {
    "id": "seed-zelda-botw",
    "targetGameId": "zelda-botw",
    "persona": "核心目标玩家：想玩《塞尔达传说：旷野之息》这类开放世界、physics play、free solution体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=塞尔达传说：旷野之息",
      "coreTags=open_world, physics_play, free_solution, exploration, discovery, low_guidance, adventure",
      "avoidSignals=needs_strong_story, needs_clear_objectives"
    ]
  },
  {
    "id": "seed-elden-ring",
    "targetGameId": "elden-ring",
    "persona": "核心目标玩家：想玩《艾尔登法环》这类开放世界、soulslike、high difficulty体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "D",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=艾尔登法环",
      "coreTags=open_world, soulslike, high_difficulty, dark_fantasy, combat_mastery, route_discovery, high_pressure, low_guidance",
      "avoidSignals=low_pressure, no_high_difficulty, no_death_penalty"
    ]
  },
  {
    "id": "seed-rdr2",
    "targetGameId": "rdr2",
    "persona": "核心目标玩家：想玩《荒野大镖客2》这类开放世界、cinematic story、slow burn体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=荒野大镖客2",
      "coreTags=open_world, cinematic_story, slow_burn, immersion, realistic_world, travel_feeling, character_story, solo",
      "avoidSignals=needs_fast_feedback, no_slow_pace"
    ]
  },
  {
    "id": "seed-cyberpunk-2077",
    "targetGameId": "cyberpunk-2077",
    "persona": "核心目标玩家：想玩《赛博朋克2077》这类开放世界、sci fi、first person体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "B",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=赛博朋克2077",
      "coreTags=open_world, sci_fi, first_person, story, buildcraft, city_exploration, cinematic",
      "avoidSignals=no_mature_theme, no_open_world"
    ]
  },
  {
    "id": "seed-witcher-3",
    "targetGameId": "witcher-3",
    "persona": "核心目标玩家：想玩《巫师3》这类开放世界、dark fantasy、剧情沉浸体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "D",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=巫师3",
      "coreTags=open_world, dark_fantasy, story, choice_consequence, quest_writing, exploration",
      "avoidSignals=no_heavy_story, no_open_world"
    ]
  },
  {
    "id": "seed-palworld",
    "targetGameId": "palworld",
    "persona": "核心目标玩家：想玩《幻兽帕鲁》这类开放世界、creature collecting、生存推进体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=幻兽帕鲁",
      "coreTags=open_world, creature_collecting, survival, base_building, automation, crafting, exploration",
      "avoidSignals=no_sandbox, no_survival, no_crafting"
    ]
  },
  {
    "id": "seed-skyrim",
    "targetGameId": "skyrim",
    "persona": "核心目标玩家：想玩《上古卷轴5》这类开放世界、roleplay、fantasy体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=上古卷轴5",
      "coreTags=open_world, roleplay, fantasy, self_directed, mod_friendly, exploration, sandbox_rpg, solo",
      "avoidSignals=needs_tight_story, needs_modern_combat"
    ]
  },
  {
    "id": "seed-baldurs-gate-3",
    "targetGameId": "baldurs-gate-3",
    "persona": "核心目标玩家：想玩《博德之门3》这类剧情沉浸、choice consequence、crpg体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=博德之门3",
      "coreTags=story, choice_consequence, crpg, turn_based, party_building, roleplay, long_session, solo",
      "avoidSignals=no_heavy_text, no_complex_system, no_long_session"
    ]
  },
  {
    "id": "seed-disco-elysium",
    "targetGameId": "disco-elysium",
    "persona": "核心目标玩家：想玩《极乐迪斯科》这类剧情沉浸、heavy text、dialogue体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=极乐迪斯科",
      "coreTags=story, heavy_text, dialogue, detective, roleplay, philosophical, no_combat",
      "avoidSignals=no_heavy_text, needs_action, needs_fast_feedback"
    ]
  },
  {
    "id": "seed-persona-5-royal",
    "targetGameId": "persona-5-royal",
    "persona": "核心目标玩家：想玩《女神异闻录5 皇家版》这类剧情沉浸、character bond、turn based体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=女神异闻录5 皇家版",
      "coreTags=story, character_bond, turn_based, school_life, anime, calendar, long_term, solo",
      "avoidSignals=no_anime, no_long_story, no_turn_based"
    ]
  },
  {
    "id": "seed-final-fantasy-xvi",
    "targetGameId": "final-fantasy-xvi",
    "persona": "核心目标玩家：想玩《最终幻想 XVI》这类剧情沉浸、cinematic、action combat体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=最终幻想 XVI",
      "coreTags=story, cinematic, action_combat, fantasy, epic, character_drama, solo, combat_mastery",
      "avoidSignals=no_cinematic, needs_open_world, no_action"
    ]
  },
  {
    "id": "seed-detroit-become-human",
    "targetGameId": "detroit-become-human",
    "persona": "核心目标玩家：想玩《底特律：化身为人》这类interactive movie、choice consequence、cinematic体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=底特律：化身为人",
      "coreTags=interactive_movie, choice_consequence, cinematic, branching_story, sci_fi, low_execution, solo",
      "avoidSignals=needs_deep_gameplay, no_cinematic"
    ]
  },
  {
    "id": "seed-star-rail",
    "targetGameId": "star-rail",
    "persona": "核心目标玩家：想玩《崩坏：星穹铁道》这类剧情沉浸、turn based、character collection体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=崩坏：星穹铁道",
      "coreTags=story, turn_based, character_collection, anime, team_building, long_term, sci_fi, solo",
      "avoidSignals=no_collection, no_long_term, no_turn_based"
    ]
  },
  {
    "id": "seed-life-is-strange",
    "targetGameId": "life-is-strange",
    "persona": "核心目标玩家：想玩《Life is Strange》这类剧情沉浸、choice consequence、character bond体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Life is Strange",
      "coreTags=story, choice_consequence, character_bond, episodic, low_pressure, dialogue",
      "avoidSignals=needs_action, no_teen_drama, no_slow_pace"
    ]
  },
  {
    "id": "seed-outer-wilds",
    "targetGameId": "outer-wilds",
    "persona": "核心目标玩家：想玩《星际拓荒》这类探索发现、mystery、knowledge progression体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=星际拓荒",
      "coreTags=exploration, mystery, knowledge_progression, space, puzzle, discovery, no_combat",
      "avoidSignals=needs_clear_objectives, no_exploration, no_mystery"
    ]
  },
  {
    "id": "seed-slay-the-spire",
    "targetGameId": "slay-the-spire",
    "persona": "核心目标玩家：想玩《杀戮尖塔》这类牌组构筑、反复构筑、planning体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "C",
      "Q06_FAILURE": "B",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=杀戮尖塔",
      "coreTags=deckbuilder, roguelike, planning, run_based, risk_reward, low_reflex, system_mastery, optimization",
      "avoidSignals=needs_story, needs_action, no_failure_retry"
    ]
  },
  {
    "id": "seed-balatro",
    "targetGameId": "balatro",
    "persona": "核心目标玩家：想玩《Balatro》这类牌组构筑、poker、combo体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "B",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Balatro",
      "coreTags=deckbuilder, poker, combo, short_session, multiplier, run_based, system_mastery",
      "avoidSignals=needs_story, no_card_logic"
    ]
  },
  {
    "id": "seed-hades",
    "targetGameId": "hades",
    "persona": "核心目标玩家：想玩《哈迪斯》这类action roguelike、run based、reflex体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "A",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "B",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=哈迪斯",
      "coreTags=action_roguelike, run_based, reflex, buildcraft, story, fast_feedback, combat_mastery",
      "avoidSignals=no_reflex, no_failure_retry, low_pressure_only"
    ]
  },
  {
    "id": "seed-monster-train",
    "targetGameId": "monster-train",
    "persona": "核心目标玩家：想玩《怪物火车》这类牌组构筑、反复构筑、lane strategy体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=怪物火车",
      "coreTags=deckbuilder, roguelike, lane_strategy, planning, combo, run_based, low_reflex, solo",
      "avoidSignals=needs_story, needs_action"
    ]
  },
  {
    "id": "seed-vampire-survivors",
    "targetGameId": "vampire-survivors",
    "persona": "核心目标玩家：想玩《吸血鬼幸存者》这类short session、auto attack、horde survival体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=吸血鬼幸存者",
      "coreTags=short_session, auto_attack, horde_survival, low_execution, number_growth, fast_feedback, solo",
      "avoidSignals=needs_deep_story, needs_precision_control"
    ]
  },
  {
    "id": "seed-inscryption",
    "targetGameId": "inscryption",
    "persona": "核心目标玩家：想玩《邪恶冥刻》这类card game、narrative trick、恐怖压迫体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "D",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=邪恶冥刻",
      "coreTags=card_game, narrative_trick, horror, puzzle, rule_twist, mystery",
      "avoidSignals=no_horror, needs_pure_strategy, no_weird_story"
    ]
  },
  {
    "id": "seed-civilization-vi",
    "targetGameId": "civilization-vi",
    "persona": "核心目标玩家：想玩《文明6》这类4x strategy、long session、macro planning体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "C",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=文明6",
      "coreTags=4x_strategy, long_session, macro_planning, empire_building, turn_based, optimization, solo",
      "avoidSignals=short_session_only, no_complex_system, no_long_session"
    ]
  },
  {
    "id": "seed-into-the-breach",
    "targetGameId": "into-the-breach",
    "persona": "核心目标玩家：想玩《Into the Breach》这类战术决策、puzzle strategy、turn based体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Into the Breach",
      "coreTags=tactics, puzzle_strategy, turn_based, perfect_information, short_session, planning",
      "avoidSignals=needs_story, needs_random_growth"
    ]
  },
  {
    "id": "seed-stardew-valley",
    "targetGameId": "stardew-valley",
    "persona": "核心目标玩家：想玩《星露谷物语》这类田园经营、生活模拟、治愈低压体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "A",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=星露谷物语",
      "coreTags=farming, life_sim, cozy, routine, relationship, collection, low_pressure",
      "avoidSignals=needs_fast_feedback, no_repetition, no_cozy"
    ]
  },
  {
    "id": "seed-animal-crossing",
    "targetGameId": "animal-crossing",
    "persona": "核心目标玩家：想玩《集合啦！动物森友会》这类治愈低压、decoration、collection体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "B",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=集合啦！动物森友会",
      "coreTags=cozy, decoration, collection, daily_routine, island_design, low_pressure, self_expression",
      "avoidSignals=needs_challenge, needs_fast_feedback, no_daily_routine"
    ]
  },
  {
    "id": "seed-the-sims-4",
    "targetGameId": "the-sims-4",
    "persona": "核心目标玩家：想玩《模拟人生4》这类生活模拟、house building、character creation体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "B",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=模拟人生4",
      "coreTags=life_sim, house_building, character_creation, sandbox_story, self_expression, low_pressure, solo",
      "avoidSignals=needs_clear_objectives, needs_combat, no_sandbox"
    ]
  },
  {
    "id": "seed-dave-the-diver",
    "targetGameId": "dave-the-diver",
    "persona": "核心目标玩家：想玩《潜水员戴夫》这类探索发现、restaurant management、治愈低压体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "A",
      "Q10_RHYTHM": "B",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=潜水员戴夫",
      "coreTags=exploration, restaurant_management, cozy, humor, medium_session, collection, light_action",
      "avoidSignals=no_management, no_exploration"
    ]
  },
  {
    "id": "seed-spiritfarer",
    "targetGameId": "spiritfarer",
    "persona": "核心目标玩家：想玩《Spiritfarer》这类治愈低压、emotional story、经营管理体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "A",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=Spiritfarer",
      "coreTags=cozy, emotional_story, management, farewell, crafting, low_pressure, character_bond",
      "avoidSignals=no_emotional_story, needs_fast_feedback"
    ]
  },
  {
    "id": "seed-unpacking",
    "targetGameId": "unpacking",
    "persona": "核心目标玩家：想玩《Unpacking》这类治愈低压、organization、environmental story体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "A",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Unpacking",
      "coreTags=cozy, organization, environmental_story, short_session, low_pressure, object_placement",
      "avoidSignals=needs_challenge, needs_long_progression, needs_combat"
    ]
  },
  {
    "id": "seed-coral-island",
    "targetGameId": "coral-island",
    "persona": "核心目标玩家：想玩《珊瑚岛》这类田园经营、生活模拟、治愈低压体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "A",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=珊瑚岛",
      "coreTags=farming, life_sim, cozy, relationship, collection, town_restoration",
      "avoidSignals=needs_fast_feedback, no_repetition"
    ]
  },
  {
    "id": "seed-story-of-seasons",
    "targetGameId": "story-of-seasons",
    "persona": "核心目标玩家：想玩《牧场物语》这类田园经营、生活模拟、治愈低压体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "A",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "C"
    },
    "notes": [
      "target=牧场物语",
      "coreTags=farming, life_sim, cozy, relationship, routine, long_term",
      "avoidSignals=needs_fast_feedback, no_repetition"
    ]
  },
  {
    "id": "seed-minecraft",
    "targetGameId": "minecraft",
    "persona": "核心目标玩家：想玩《我的世界》这类沙盒自由、building、生存推进体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "B",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=我的世界",
      "coreTags=sandbox, building, survival, creative, exploration, self_directed, crafting",
      "avoidSignals=needs_clear_objectives, no_sandbox, no_building"
    ]
  },
  {
    "id": "seed-terraria",
    "targetGameId": "terraria",
    "persona": "核心目标玩家：想玩《泰拉瑞亚》这类沙盒自由、采集制作、探索发现体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "D",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "B",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=泰拉瑞亚",
      "coreTags=sandbox, crafting, exploration, boss_progression, gear_growth, 2d_action, building",
      "avoidSignals=needs_clear_objectives, no_action, no_sandbox"
    ]
  },
  {
    "id": "seed-dont-starve",
    "targetGameId": "dont-starve",
    "persona": "核心目标玩家：想玩《饥荒》这类生存推进、采集制作、resource pressure体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=饥荒",
      "coreTags=survival, crafting, resource_pressure, dark_humor, self_directed, failure_pressure, solo",
      "avoidSignals=low_pressure, no_survival, no_failure_punishment"
    ]
  },
  {
    "id": "seed-rimworld",
    "targetGameId": "rimworld",
    "persona": "核心目标玩家：想玩《RimWorld》这类colony sim、emergent story、resource management体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "C",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=RimWorld",
      "coreTags=colony_sim, emergent_story, resource_management, survival, systemic, high_complexity, solo",
      "avoidSignals=no_complex_system, low_pressure, needs_short_session"
    ]
  },
  {
    "id": "seed-dyson-sphere-program",
    "targetGameId": "dyson-sphere-program",
    "persona": "核心目标玩家：想玩《戴森球计划》这类factory、automation、macro planning体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "C",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=戴森球计划",
      "coreTags=factory, automation, macro_planning, resource_chain, sci_fi, optimization",
      "avoidSignals=no_factory, no_optimization, needs_story"
    ]
  },
  {
    "id": "seed-factorio",
    "targetGameId": "factorio",
    "persona": "核心目标玩家：想玩《Factorio》这类factory、automation、optimization体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "B",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "C",
      "Q06_FAILURE": "B",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Factorio",
      "coreTags=factory, automation, optimization, resource_chain, defense, system_mastery",
      "avoidSignals=no_factory, no_optimization, needs_story"
    ]
  },
  {
    "id": "seed-it-takes-two",
    "targetGameId": "it-takes-two",
    "persona": "核心目标玩家：想玩《双人成行》这类fixed coop、two player、puzzle platforming体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "B",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=双人成行",
      "coreTags=fixed_coop, two_player, puzzle_platforming, story, variety, teamwork",
      "avoidSignals=solo_only, no_coop, no_friend_available"
    ]
  },
  {
    "id": "seed-overcooked-2",
    "targetGameId": "overcooked-2",
    "persona": "核心目标玩家：想玩《胡闹厨房2》这类fixed coop、派对混乱、time pressure体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=胡闹厨房2",
      "coreTags=fixed_coop, party, time_pressure, coordination, cooking, short_session, chaos_fun, coop",
      "avoidSignals=solo_only, no_time_pressure, no_coop"
    ]
  },
  {
    "id": "seed-eggy-party",
    "targetGameId": "eggy-party",
    "persona": "核心目标玩家：想玩《蛋仔派对》这类派对混乱、short session、chaos fun体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=蛋仔派对",
      "coreTags=party, short_session, chaos_fun, ugc, cute, fast_feedback",
      "avoidSignals=solo_only, no_multiplayer, needs_deep_system"
    ]
  },
  {
    "id": "seed-sky",
    "targetGameId": "sky",
    "persona": "核心目标玩家：想玩《光·遇》这类social cozy、探索发现、companionship体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "A",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=光·遇",
      "coreTags=social_cozy, exploration, companionship, low_pressure, aesthetic, soft_social",
      "avoidSignals=no_social, needs_clear_objectives, needs_combat"
    ]
  },
  {
    "id": "seed-human-fall-flat",
    "targetGameId": "human-fall-flat",
    "persona": "核心目标玩家：想玩《人类一败涂地》这类physics comedy、coop、puzzle platforming体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=人类一败涂地",
      "coreTags=physics_comedy, coop, puzzle_platforming, chaos_fun, short_session, low_pressure",
      "avoidSignals=needs_precision, solo_only, no_chaos"
    ]
  },
  {
    "id": "seed-super-mario-party",
    "targetGameId": "super-mario-party",
    "persona": "核心目标玩家：想玩《超级马力欧派对》这类派对混乱、local multiplayer、mini games体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=超级马力欧派对",
      "coreTags=party, local_multiplayer, mini_games, family_fun, short_session, randomness",
      "avoidSignals=solo_only, no_randomness, needs_deep_strategy"
    ]
  },
  {
    "id": "seed-monument-valley-2",
    "targetGameId": "monument-valley-2",
    "persona": "核心目标玩家：想玩《纪念碑谷2》这类逻辑解谜、visual trick、short session体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "D",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "B",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=纪念碑谷2",
      "coreTags=puzzle, visual_trick, short_session, low_pressure, aesthetic, guided",
      "avoidSignals=needs_challenge, needs_long_game"
    ]
  },
  {
    "id": "seed-baba-is-you",
    "targetGameId": "baba-is-you",
    "persona": "核心目标玩家：想玩《Baba Is You》这类逻辑解谜、logic、rule manipulation体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "A",
      "Q02_LOOP": "B",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "B",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Baba Is You",
      "coreTags=puzzle, logic, rule_manipulation, high_difficulty, system_mastery, low_reflex",
      "avoidSignals=low_pressure_only, needs_story, no_hard_puzzle"
    ]
  },
  {
    "id": "seed-portal-2",
    "targetGameId": "portal-2",
    "persona": "核心目标玩家：想玩《传送门2》这类逻辑解谜、spatial logic、physics体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "B",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=传送门2",
      "coreTags=puzzle, spatial_logic, physics, humor, guided, first_person, medium_session, solo",
      "avoidSignals=motion_sick_sensitive, no_puzzle"
    ]
  },
  {
    "id": "seed-return-of-obra-dinn",
    "targetGameId": "return-of-obra-dinn",
    "persona": "核心目标玩家：想玩《奥伯拉丁的回归》这类deduction、mystery、observation体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=奥伯拉丁的回归",
      "coreTags=deduction, mystery, observation, logic, no_combat, slow_thinking, detective",
      "avoidSignals=needs_action, no_deduction, needs_clear_solution"
    ]
  },
  {
    "id": "seed-animal-well",
    "targetGameId": "animal-well",
    "persona": "核心目标玩家：想玩《动物井》这类探索发现、探索成长、mystery体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=动物井",
      "coreTags=exploration, metroidvania, mystery, puzzle, compact_world, discovery",
      "avoidSignals=needs_clear_objectives, no_mystery"
    ]
  },
  {
    "id": "seed-tunic",
    "targetGameId": "tunic",
    "persona": "核心目标玩家：想玩《Tunic》这类探索发现、mystery、manual discovery体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "C",
      "Q02_LOOP": "C",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "C",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "C",
      "Q11_TONE": "C",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=Tunic",
      "coreTags=exploration, mystery, manual_discovery, action_adventure, puzzle, compact_world",
      "avoidSignals=needs_clear_objectives, no_action"
    ]
  },
  {
    "id": "seed-tetris-effect",
    "targetGameId": "tetris-effect",
    "persona": "核心目标玩家：想玩《俄罗斯方块效应》这类short session、逻辑解谜、flow state体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "C",
      "Q04_SOCIAL": "C",
      "Q05_PRESSURE": "A",
      "Q06_FAILURE": "A",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=俄罗斯方块效应",
      "coreTags=short_session, puzzle, flow_state, music, score_chase, fast_feedback, low_pressure, reflex",
      "avoidSignals=needs_story, no_score_chase"
    ]
  },
  {
    "id": "seed-plants-vs-zombies",
    "targetGameId": "plants-vs-zombies",
    "persona": "核心目标玩家：想玩《植物大战僵尸》这类塔防解题、short session、light strategy体验；能接受它的主要节奏和门槛，最在意玩法是否对味，而不是平台、价格或热度。",
    "answers": {
      "Q01_MOTIVE": "D",
      "Q02_LOOP": "A",
      "Q03_MASTERY": "D",
      "Q04_SOCIAL": "B",
      "Q05_PRESSURE": "D",
      "Q06_FAILURE": "C",
      "Q07_STORY": "A",
      "Q08_EXPLORATION": "C",
      "Q09_CREATE_MANAGE": "C",
      "Q10_RHYTHM": "A",
      "Q11_TONE": "A",
      "Q12_HARD_AVOID": "D"
    },
    "notes": [
      "target=植物大战僵尸",
      "coreTags=tower_defense, short_session, light_strategy, cute, fast_feedback, accessible, solo",
      "avoidSignals=needs_deep_strategy, needs_story"
    ]
  }
];

export const GOLDEN_SEEDS = goldenSeeds;
